### ISSUE TITLE
can't work...

### ISSUE THREAD

**Issue by RocherKong** [scheshan/DotNetClub#3]
I have setup redis and add usersecrets to the project,but it still not work...is there other tips about config?

**Comment by scheshan** [comment]
Did u run the database scripts to create tables?
Or u can debug in VS and paste the exceptions and stack traces here

**Comment by RocherKong** [comment]
Thanks ,I have solved the problem.that caused by not add runtime enviroment into project.json.
the added code is following:
`  "runtimes": {
    "win10-x64": {},
    "win81-x64": {},
    "win8-x64": {},
    "win7-x64": {}
  },`

**Comment by yj-smart** [comment]
IHostingEnvironment not ConfigureNLog method
